/*
 * Generated by gdbus-codegen 2.56.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __EXAMPLEGDBUSGENERATED_H__
#define __EXAMPLEGDBUSGENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for cn.RTplay.Gdbus.Example */

#define GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE (gateway_cn_rtplay_gdbus_example_get_type ())
#define GATEWAY_CN_RTPLAY_GDBUS_EXAMPLE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE, GatewayCnRTplayGdbusExample))
#define GATEWAY_IS_CN_RTPLAY_GDBUS_EXAMPLE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE))
#define GATEWAY_CN_RTPLAY_GDBUS_EXAMPLE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE, GatewayCnRTplayGdbusExampleIface))

struct _GatewayCnRTplayGdbusExample;
typedef struct _GatewayCnRTplayGdbusExample GatewayCnRTplayGdbusExample;
typedef struct _GatewayCnRTplayGdbusExampleIface GatewayCnRTplayGdbusExampleIface;

struct _GatewayCnRTplayGdbusExampleIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_my_method1) (
    GatewayCnRTplayGdbusExample *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_InArg);

  gboolean (*handle_my_method2) (
    GatewayCnRTplayGdbusExample *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_InArg);

  void (*my_signal1) (
    GatewayCnRTplayGdbusExample *object,
    const gchar *arg_Value);

  void (*my_signal2) (
    GatewayCnRTplayGdbusExample *object,
    GVariant *arg_Value);

};

GType gateway_cn_rtplay_gdbus_example_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *gateway_cn_rtplay_gdbus_example_interface_info (void);
guint gateway_cn_rtplay_gdbus_example_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void gateway_cn_rtplay_gdbus_example_complete_my_method1 (
    GatewayCnRTplayGdbusExample *object,
    GDBusMethodInvocation *invocation,
    const gchar *OutArg);

void gateway_cn_rtplay_gdbus_example_complete_my_method2 (
    GatewayCnRTplayGdbusExample *object,
    GDBusMethodInvocation *invocation,
    GVariant *OutArg);



/* D-Bus signal emissions functions: */
void gateway_cn_rtplay_gdbus_example_emit_my_signal1 (
    GatewayCnRTplayGdbusExample *object,
    const gchar *arg_Value);

void gateway_cn_rtplay_gdbus_example_emit_my_signal2 (
    GatewayCnRTplayGdbusExample *object,
    GVariant *arg_Value);



/* D-Bus method calls: */
void gateway_cn_rtplay_gdbus_example_call_my_method1 (
    GatewayCnRTplayGdbusExample *proxy,
    const gchar *arg_InArg,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gateway_cn_rtplay_gdbus_example_call_my_method1_finish (
    GatewayCnRTplayGdbusExample *proxy,
    gchar **out_OutArg,
    GAsyncResult *res,
    GError **error);

gboolean gateway_cn_rtplay_gdbus_example_call_my_method1_sync (
    GatewayCnRTplayGdbusExample *proxy,
    const gchar *arg_InArg,
    gchar **out_OutArg,
    GCancellable *cancellable,
    GError **error);

void gateway_cn_rtplay_gdbus_example_call_my_method2 (
    GatewayCnRTplayGdbusExample *proxy,
    GVariant *arg_InArg,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gateway_cn_rtplay_gdbus_example_call_my_method2_finish (
    GatewayCnRTplayGdbusExample *proxy,
    GVariant **out_OutArg,
    GAsyncResult *res,
    GError **error);

gboolean gateway_cn_rtplay_gdbus_example_call_my_method2_sync (
    GatewayCnRTplayGdbusExample *proxy,
    GVariant *arg_InArg,
    GVariant **out_OutArg,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_PROXY (gateway_cn_rtplay_gdbus_example_proxy_get_type ())
#define GATEWAY_CN_RTPLAY_GDBUS_EXAMPLE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_PROXY, GatewayCnRTplayGdbusExampleProxy))
#define GATEWAY_CN_RTPLAY_GDBUS_EXAMPLE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_PROXY, GatewayCnRTplayGdbusExampleProxyClass))
#define GATEWAY_CN_RTPLAY_GDBUS_EXAMPLE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_PROXY, GatewayCnRTplayGdbusExampleProxyClass))
#define GATEWAY_IS_CN_RTPLAY_GDBUS_EXAMPLE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_PROXY))
#define GATEWAY_IS_CN_RTPLAY_GDBUS_EXAMPLE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_PROXY))

typedef struct _GatewayCnRTplayGdbusExampleProxy GatewayCnRTplayGdbusExampleProxy;
typedef struct _GatewayCnRTplayGdbusExampleProxyClass GatewayCnRTplayGdbusExampleProxyClass;
typedef struct _GatewayCnRTplayGdbusExampleProxyPrivate GatewayCnRTplayGdbusExampleProxyPrivate;

struct _GatewayCnRTplayGdbusExampleProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  GatewayCnRTplayGdbusExampleProxyPrivate *priv;
};

struct _GatewayCnRTplayGdbusExampleProxyClass
{
  GDBusProxyClass parent_class;
};

GType gateway_cn_rtplay_gdbus_example_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GatewayCnRTplayGdbusExampleProxy, g_object_unref)
#endif

void gateway_cn_rtplay_gdbus_example_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GatewayCnRTplayGdbusExample *gateway_cn_rtplay_gdbus_example_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
GatewayCnRTplayGdbusExample *gateway_cn_rtplay_gdbus_example_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void gateway_cn_rtplay_gdbus_example_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GatewayCnRTplayGdbusExample *gateway_cn_rtplay_gdbus_example_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GatewayCnRTplayGdbusExample *gateway_cn_rtplay_gdbus_example_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON (gateway_cn_rtplay_gdbus_example_skeleton_get_type ())
#define GATEWAY_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON, GatewayCnRTplayGdbusExampleSkeleton))
#define GATEWAY_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON, GatewayCnRTplayGdbusExampleSkeletonClass))
#define GATEWAY_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON, GatewayCnRTplayGdbusExampleSkeletonClass))
#define GATEWAY_IS_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON))
#define GATEWAY_IS_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GATEWAY_TYPE_CN_RTPLAY_GDBUS_EXAMPLE_SKELETON))

typedef struct _GatewayCnRTplayGdbusExampleSkeleton GatewayCnRTplayGdbusExampleSkeleton;
typedef struct _GatewayCnRTplayGdbusExampleSkeletonClass GatewayCnRTplayGdbusExampleSkeletonClass;
typedef struct _GatewayCnRTplayGdbusExampleSkeletonPrivate GatewayCnRTplayGdbusExampleSkeletonPrivate;

struct _GatewayCnRTplayGdbusExampleSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  GatewayCnRTplayGdbusExampleSkeletonPrivate *priv;
};

struct _GatewayCnRTplayGdbusExampleSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType gateway_cn_rtplay_gdbus_example_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GatewayCnRTplayGdbusExampleSkeleton, g_object_unref)
#endif

GatewayCnRTplayGdbusExample *gateway_cn_rtplay_gdbus_example_skeleton_new (void);


G_END_DECLS

#endif /* __EXAMPLEGDBUSGENERATED_H__ */
